apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: writer
          image: jessehantula/log-output-writer:1.1
          volumeMounts:
            - mountPath: /usr/src/app/files/
              name: shared-logs
        - name: reader
          image: jessehantula/log-output-reader:1.1
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/files/
              name: shared-logs
